module-name: warden
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/warden/operator:0.12.4
  - europe-docker.pkg.dev/kyma-project/prod/warden/admission:0.12.4
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
