name: 'Setup go'
description: 'Action for the go setup'

inputs:
  version:
    description: 'go version to checkout'
    required: true
    default: '1.22'

runs:
  using: 'composite'
  steps:
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.version }}
