name: integration tests (push)

on:
  push:
    branches: [ "main", "release-*" ]
    paths-ignore:
      - '**.md'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rebase
      - uses: ./.github/actions/create-k3d-cluster
      - uses: ./.github/actions/setup-go
      - name: run test
        run: make verify-on-cluster
        env:
          IMG_DIRECTORY: prod
          IMG_VERSION: ${{github.sha}}
      - name: show warden logs
        if: failure()
        run: kubectl logs -l app=warden -n kyma-system --prefix=true;
