name: pull

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  unit-tests:
    uses: ./.github/workflows/_unit-tests.yaml

  gitleaks:
    uses: ./.github/workflows/_gitleaks.yaml

  builds:
    needs: [unit-tests, gitleaks]
    uses: ./.github/workflows/_build.yaml

  integrations:
    needs: builds
    uses: ./.github/workflows/_integration-tests.yaml
    with:
      directory-version: dev
      image-version: "PR-${{ github.event.number }}"
