name: unit tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rebase
      - uses: ./.github/actions/setup-go
      - name: fmt and unit tests
        run: make verify
